INSERT INTO wyj.article (goods_name, goods_code, goods_count, file_id, sponsor, memo, delete_flag, price, discount, type) VALUES ('德芙', '1', 20, 'http://localhost:8080/images/2.jpg', '玛氏食品公司', '德芙是世界最大宠物食品和休闲食品制造商美国跨国食品公司玛氏（Mars）公司在中国推出的系列产品，1989年进入中国。
', 1, 99, 199, 1);
INSERT INTO wyj.article (goods_name, goods_code, goods_count, file_id, sponsor, memo, delete_flag, price, discount, type) VALUES ('ysl', '2', 100, 'http://localhost:8080/images/1.jpg', '伊夫圣罗兰', 'YSL的简称，中文译名圣罗兰，是法国著名奢侈品牌，由1936年8月1日出生于法属北非阿尔及利亚的伊夫圣罗兰先生创立，主要有时装、护肤品，香水，箱包，眼镜，配饰等。', 2, 320, 500, 2);
INSERT INTO wyj.article (goods_name, goods_code, goods_count, file_id, sponsor, memo, delete_flag, price, discount, type) VALUES ('红焖羊肉', '3', 50, 'http://localhost:8080/images/hmyr.jpg', 'aaa', '红焖羊肉，以肉嫩、味鲜、汤醇、价廉深受各路食客的好评，很快便风靡牧野。', 3, 30, 50, 3);
INSERT INTO wyj.article (goods_name, goods_code, goods_count, file_id, sponsor, memo, delete_flag, price, discount, type) VALUES ('糖醋排骨', '4', 66, 'http://localhost:8080/images/tcpg.jpg', 'aaa', '糖醋排骨是糖醋菜中具有代表性的一道大众喜爱的传统菜，它选用新鲜猪子排作料，肉质鲜嫩，成莱色泽红亮油润，口味香脆酸甜，颇受江南一带食者的欢迎。', 4, 25, 45, 3);
INSERT INTO wyj.article (goods_name, goods_code, goods_count, file_id, sponsor, memo, delete_flag, price, discount, type) VALUES ('沸腾虾', '5', 88, 'http://localhost:8080/images/ftx.jpg', 'aaa', '香辣鲜美，色泽诱人', 5, 40, 60, 4);
INSERT INTO wyj.article (goods_name, goods_code, goods_count, file_id, sponsor, memo, delete_flag, price, discount, type) VALUES ('松鼠桂鱼', '6', 22, 'http://localhost:8080/images/ssgy.jpg', 'aaa', '这道菜成菜后，形如松鼠、外脆里嫩、色泽橘黄，酸甜适口，并有松红香味', 6, 35, 70, 4);
INSERT INTO wyj.article (goods_name, goods_code, goods_count, file_id, sponsor, memo, delete_flag, price, discount, type) VALUES ('好丽友', '7', 30, 'http://localhost:8080/images/3.jpg', 'aaa', '好丽友 aaaaa啊啊ad撒打算', 7, 19, 30, 5);
INSERT INTO wyj.article (goods_name, goods_code, goods_count, file_id, sponsor, memo, delete_flag, price, discount, type) VALUES ('MAC ', '8', 20, 'http://localhost:8080/images/4.jpg', '雅诗兰黛集团', 'M·A·C彩妆是出自于加拿大的彩妆品牌，它以其耀眼光芒在品牌建立的初期吸引了雅诗兰黛集团的注意将其收入集团内。M·A·C的优异特质才得以被发掘、散播，从北美地区远扬至欧亚各国', 8, 230, 330, 2);
INSERT INTO wyj.article (goods_name, goods_code, goods_count, file_id, sponsor, memo, delete_flag, price, discount, type) VALUES ('迪奥', '9', 20, 'http://localhost:8080/images/6.jpg', '路威酩轩集团', '克里斯汀·迪奥（英语：Christian Dior），简称迪奥（Dior），是法国著名时尚消费品牌。亦为全球最大的高级时尚品牌控股公司', 9, 1000, 1500, 6);
INSERT INTO wyj.article (goods_name, goods_code, goods_count, file_id, sponsor, memo, delete_flag, price, discount, type) VALUES ('解忧杂货铺', '10', 30, 'http://localhost:8080/images/5.jpg', '东野圭吾', '《解忧杂货店》是日本作家东野圭吾写作的奇幻温情小说。2011年于《小说野性时代》连载', 10, 50, 70, 7);
INSERT INTO wyj.article (goods_name, goods_code, goods_count, file_id, sponsor, memo, delete_flag, price, discount, type) VALUES ('德芙巧克力', '1', 20, 'http://localhost:8080/images/10.jpg', '浪子', '德芙是世界最大宠物食品和休闲食品制造商美国跨国食品公司玛氏（Mars）公司在中国推出的系列产品，1989年进入中国。
', 1, 99, 199, 1);
INSERT INTO wyj.article (goods_name, goods_code, goods_count, file_id, sponsor, memo, delete_flag, price, discount, type) VALUES ('ysl', '2', 100, 'http://localhost:8080/images/11.jpg', '伊夫圣罗兰', 'YSL的简称，中文译名圣罗兰，是法国著名奢侈品牌，由1936年8月1日出生于法属北非阿尔及利亚的伊夫圣罗兰先生创立，主要有时装、护肤品，香水，箱包，眼镜，配饰等。', 2, 320, 500, 2);
INSERT INTO wyj.article (goods_name, goods_code, goods_count, file_id, sponsor, memo, delete_flag, price, discount, type) VALUES ('资生堂', '13', 30, 'http://localhost:8080/images/7.jpg', '日本', '日本进口资生堂洗颜专科珊珂洗面奶洁面乳120g三支装', 13, 110, 230, 8);
INSERT INTO wyj.article (goods_name, goods_code, goods_count, file_id, sponsor, memo, delete_flag, price, discount, type) VALUES ('士力架', '14', 100, 'http://localhost:8080/images/8.jpg', '玛氏食品公司', '补充能量 横扫饥饿 活力无限', 14, 50, 100, 5);